"""catalogue embeddings

Revision ID: 1465ab498c89
Revises: 11b9d7e15735
Create Date: 2026-07-29 11:41:06.007301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '1465ab498c89'
down_revision: Union[str, Sequence[str], None] = '11b9d7e15735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheme_catalogue', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # HNSW over cosine distance. IVFFlat would need a training pass and a
    # tuned list count; at 4,810 rows HNSW builds in seconds and needs neither.
    op.execute("CREATE INDEX ix_cat_embedding ON scheme_catalogue "
               "USING hnsw (embedding vector_cosine_ops)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_cat_embedding")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheme_catalogue', 'embedding')
    # ### end Alembic commands ###
