"""scheme_catalogue

Revision ID: aeebd45ecf70
Revises: c260a74d5f97
Create Date: 2026-07-29 10:34:48.942815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aeebd45ecf70'
down_revision: Union[str, Sequence[str], None] = 'c260a74d5f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheme_catalogue',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ministry', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index('ix_cat_ministry', 'scheme_catalogue', ['ministry'], unique=False)
    op.create_index('ix_cat_state', 'scheme_catalogue', ['state'], unique=False)
    op.create_index(op.f('ix_scheme_catalogue_title'), 'scheme_catalogue', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheme_catalogue_title'), table_name='scheme_catalogue')
    op.drop_index('ix_cat_state', table_name='scheme_catalogue')
    op.drop_index('ix_cat_ministry', table_name='scheme_catalogue')
    op.drop_table('scheme_catalogue')
    # ### end Alembic commands ###
