"""initial schema

Revision ID: c260a74d5f97
Revises: 
Create Date: 2026-07-29 10:25:34.595091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Autogenerate renders the embedding column as pgvector.sqlalchemy.vector.VECTOR
# but does not emit the import for it.
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c260a74d5f97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # service_records.embedding is a pgvector column, so the extension has to
    # exist before the table is created. The image ships it; this makes a fresh
    # database work without a manual psql step.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directory_records',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_title', sa.Text(), nullable=False),
    sa.Column('row', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('pincode', sa.String(length=12), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dir_geo', 'directory_records', ['state', 'district'], unique=False)
    op.create_index('ix_dir_pincode', 'directory_records', ['pincode'], unique=False)
    op.create_index(op.f('ix_directory_records_dataset_id'), 'directory_records', ['dataset_id'], unique=False)
    op.create_table('link_checks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_checks_url'), 'link_checks', ['url'], unique=False)
    op.create_index('ix_link_url_time', 'link_checks', ['url', 'checked_at'], unique=False)
    op.create_table('service_records',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('jurisdiction_level', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('ministry', sa.Text(), nullable=True),
    sa.Column('life_events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('link_status', sa.String(length=24), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_records_canonical_name'), 'service_records', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_service_records_kind'), 'service_records', ['kind'], unique=False)
    op.create_index(op.f('ix_service_records_link_status'), 'service_records', ['link_status'], unique=False)
    op.create_index(op.f('ix_service_records_state'), 'service_records', ['state'], unique=False)
    op.create_index('ix_svc_jurisdiction', 'service_records', ['jurisdiction_level', 'state'], unique=False)
    op.create_index('ix_svc_kind_tier', 'service_records', ['kind', 'confidence'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('adapter', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('jurisdiction_level', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('licence', sa.String(length=128), nullable=True),
    sa.Column('licence_url', sa.Text(), nullable=True),
    sa.Column('robots_crawl_delay', sa.Float(), nullable=True),
    sa.Column('robots_allows', sa.Boolean(), nullable=True),
    sa.Column('audit_notes', sa.Text(), nullable=True),
    sa.Column('audited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_slug'), 'sources', ['slug'], unique=True)
    op.create_table('raw_documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('body_path', sa.Text(), nullable=False),
    sa.Column('body_bytes', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'content_hash', name='uq_raw_url_hash')
    )
    op.create_index(op.f('ix_raw_documents_content_hash'), 'raw_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_documents_url'), 'raw_documents', ['url'], unique=False)
    op.create_index('ix_raw_fetched_at', 'raw_documents', ['fetched_at'], unique=False)
    op.create_table('extraction_queue',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('raw_document_id', sa.BigInteger(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=128), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_document_id', name='uq_extract_doc')
    )
    op.create_index('ix_extract_claim', 'extraction_queue', ['status', 'tier', 'id'], unique=False)
    op.create_index(op.f('ix_extraction_queue_status'), 'extraction_queue', ['status'], unique=False)
    op.create_index(op.f('ix_extraction_queue_tier'), 'extraction_queue', ['tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_queue_tier'), table_name='extraction_queue')
    op.drop_index(op.f('ix_extraction_queue_status'), table_name='extraction_queue')
    op.drop_index('ix_extract_claim', table_name='extraction_queue')
    op.drop_table('extraction_queue')
    op.drop_index('ix_raw_fetched_at', table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_url'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_content_hash'), table_name='raw_documents')
    op.drop_table('raw_documents')
    op.drop_index(op.f('ix_sources_slug'), table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_svc_kind_tier', table_name='service_records')
    op.drop_index('ix_svc_jurisdiction', table_name='service_records')
    op.drop_index(op.f('ix_service_records_state'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_link_status'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_kind'), table_name='service_records')
    op.drop_index(op.f('ix_service_records_canonical_name'), table_name='service_records')
    op.drop_table('service_records')
    op.drop_index('ix_link_url_time', table_name='link_checks')
    op.drop_index(op.f('ix_link_checks_url'), table_name='link_checks')
    op.drop_table('link_checks')
    op.drop_index(op.f('ix_directory_records_dataset_id'), table_name='directory_records')
    op.drop_index('ix_dir_pincode', table_name='directory_records')
    op.drop_index('ix_dir_geo', table_name='directory_records')
    op.drop_table('directory_records')
    # ### end Alembic commands ###
