"""service_records embedding to 384d

Revision ID: f1844305f4ba
Revises: 1465ab498c89
Create Date: 2026-07-29 12:26:06.148689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'f1844305f4ba'
down_revision: Union[str, Sequence[str], None] = '1465ab498c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_records', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    # Safe as a plain type change only because every value is NULL — a 1024-d
    # vector has no meaningful projection into 384 dimensions, so there is
    # nothing to migrate. If this ever runs against populated data it must
    # become a re-embed, not a cast.
    op.execute("CREATE INDEX ix_svc_embedding ON service_records "
               "USING hnsw (embedding vector_cosine_ops)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_svc_embedding")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_records', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)
    # ### end Alembic commands ###
